name: build-image
on:
  workflow_dispatch: # manual
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm install
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm install
      - run: npm test
  build-image:
    runs-on: ubuntu-latest
    environment:
      name: Production
    needs: test
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: setup docker
        uses: docker/setup-docker-action@v5
      - uses: docker/setup-buildx-action@v3
      - name: build docker image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/dvop400-finalproject:latest
            ${{ secrets.DOCKERHUB_USER }}/dvop400-finalproject:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
